name: notify pr approve

on:
  pull_request_review:
    types: [submitted]
    branches:
      - main
      - develop

jobs:
  Notify:
    runs-on: [ubuntu-latest]
    steps:
      - name: Send Slack notification
        if: github.event.review.state == 'approved'
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "SLACK PR μ•λ¦Ό",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*${{ github.repository }}* PR μΉμΈν–μµλ‹λ‹¤π‘\n<${{ github.event.pull_request.html_url }}|PR ν™•μΈν•λ¬ κ°€κΈ°>\nRegistered by *${{ github.event.pull_request.user.login }}*\nApproved by *${{ github.actor }}*"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_PR_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
